function(target_resources TARGET VISIBILITY)
	get_target_property(OLD_RESOURCES ${TARGET} RESOURCE)
	set_target_properties(${TARGET} PROPERTIES RESOURCE "${OLD_RESOURCES} ${ARGN}")
	source_group("Resources" FILES ${ARGN})
	target_sources(${TARGET} ${VISIBILITY} ${ARGN})
	if (EMSCRIPTEN)
		foreach(f ${ARGN})
			set(FULL_PATH ${CMAKE_CURRENT_SOURCE_DIR}/${f})
			get_filename_component(FILENAME ${f} NAME)
			target_link_options(${TARGET} PRIVATE "SHELL:--embed-file ${FULL_PATH}@${FILENAME}")
		endforeach()
	endif()
endfunction()

function(ensure_existing_files)
	foreach(f ${ARGN})
		set(SOURCE_FILE "${CMAKE_CURRENT_SOURCE_DIR}/${f}")
		if(NOT EXISTS ${SOURCE_FILE})
			message(STATUS "Creating non-existing source file: ${f}")
			file(WRITE ${SOURCE_FILE} "")
		endif()
	endforeach()
endfunction()

function(set_extension_variables)
if(WIN32)
	set(EXTENSION_OS Win32 PARENT_SCOPE)
	set(EXTENSION_SYSTEM pc PARENT_SCOPE)
elseif(EMSCRIPTEN)
	set(EXTENSION_OS Win32 PARENT_SCOPE)
	set(EXTENSION_SYSTEM emscripten PARENT_SCOPE)
elseif(APPLE)
	set(EXTENSION_OS MacOS PARENT_SCOPE)
	set(EXTENSION_SYSTEM pc PARENT_SCOPE)
endif()
endfunction()
